# docker-compose.yml
version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=tpachato
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  spring_app:
    image: alaaeddinebenali/spring-tp-achat-project:11
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

  angular-app:
    image: alaaeddinebenali/angular-tp-achat-project:latest
    ports:
      - 4200:4200
    depends_on:
      - spring_app
volumes:
  db-data: